name: Selenium Test Workflow

on:
  workflow_dispatch:
  schedule:
    # During standard time (EST: UTC-5, so aim for 4:00 AM UTC)
    - cron: '0 4 * * *'
    # During daylight saving time (EDT: UTC-4, so aim for 3:00 AM UTC)
    - cron: '0 3 * * *'

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
        
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          server-id: github
          
      - name: Run Tests
        run: mvn -q -Dtest=RunTest test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-report.html
