name: Selenium Test Workflow

on:
  workflow_dispatch:
  schedule:
    # This will run every day at 9.40 PM EST time.
    # GitHub uses UTC time, so we'll specify 2:40 AM to convert from EST to UTC (EST is UTC-5, but UTC-4 during daylight saving)
    - cron: '40 2 * * *'

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
        
      - name: Set up Maven
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          server-id: github
          
      - name: Run Tests
        run: mvn -q -Dtest=RunTest test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-report.html
